"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ID = exports.Role = exports.Permission = exports.Teams = exports.Storage = exports.Locale = exports.Graphql = exports.Functions = exports.Databases = exports.Avatars = exports.Account = exports.AppwriteException = exports.Query = exports.Client = void 0;
var client_1 = require("./client");
Object.defineProperty(exports, "Client", { enumerable: true, get: function () { return client_1.Client; } });
Object.defineProperty(exports, "Query", { enumerable: true, get: function () { return client_1.Query; } });
Object.defineProperty(exports, "AppwriteException", { enumerable: true, get: function () { return client_1.AppwriteException; } });
var account_1 = require("./services/account");
Object.defineProperty(exports, "Account", { enumerable: true, get: function () { return account_1.Account; } });
var avatars_1 = require("./services/avatars");
Object.defineProperty(exports, "Avatars", { enumerable: true, get: function () { return avatars_1.Avatars; } });
var databases_1 = require("./services/databases");
Object.defineProperty(exports, "Databases", { enumerable: true, get: function () { return databases_1.Databases; } });
var functions_1 = require("./services/functions");
Object.defineProperty(exports, "Functions", { enumerable: true, get: function () { return functions_1.Functions; } });
var graphql_1 = require("./services/graphql");
Object.defineProperty(exports, "Graphql", { enumerable: true, get: function () { return graphql_1.Graphql; } });
var locale_1 = require("./services/locale");
Object.defineProperty(exports, "Locale", { enumerable: true, get: function () { return locale_1.Locale; } });
var storage_1 = require("./services/storage");
Object.defineProperty(exports, "Storage", { enumerable: true, get: function () { return storage_1.Storage; } });
var teams_1 = require("./services/teams");
Object.defineProperty(exports, "Teams", { enumerable: true, get: function () { return teams_1.Teams; } });
var permission_1 = require("./permission");
Object.defineProperty(exports, "Permission", { enumerable: true, get: function () { return permission_1.Permission; } });
var role_1 = require("./role");
Object.defineProperty(exports, "Role", { enumerable: true, get: function () { return role_1.Role; } });
var id_1 = require("./id");
Object.defineProperty(exports, "ID", { enumerable: true, get: function () { return id_1.ID; } });
